# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0002_auto_20171008_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('buff_reason', models.CharField(choices=[('工作积极', '工作积极'), ('表现良好', '表现良好'), ('加班', '加班'), ('态度积极', '态度积极'), ('贡献想法', '贡献想法')], max_length=150)),
                ('buff_details', models.CharField(blank=True, default='none', max_length=150)),
                ('hp_increase', models.IntegerField(default=5)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp.HP')),
            ],
        ),
    ]
