# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0003_buff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buff',
            name='key',
        ),
        migrations.RemoveField(
            model_name='debuff',
            name='key',
        ),
        migrations.RemoveField(
            model_name='hp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buff',
        ),
        migrations.DeleteModel(
            name='DeBuff',
        ),
        migrations.DeleteModel(
            name='HP',
        ),
    ]
