# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Check_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(default=0, max_length=10)),
                ('taken_toolkit', models.BooleanField(default=True)),
                ('check', models.IntegerField(default=0)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(auto_now=True)),
                ('check_in_area', models.CharField(max_length=20)),
                ('detailed_description', models.CharField(max_length=200, null=True)),
                ('cable', models.BooleanField(default=True)),
                ('crimping_Tool', models.BooleanField(default=True)),
                ('switch', models.BooleanField(default=True)),
                ('crystal_Head', models.BooleanField(default=True)),
                ('measuring_line', models.BooleanField(default=True)),
                ('port_module', models.BooleanField(default=True)),
                ('key', models.BooleanField(default=False)),
                ('screwdriver', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(default=0, max_length=10)),
                ('extra_area', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('extra_work_time', models.CharField(default=None, max_length=30)),
                ('refuse_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('record', models.CharField(max_length=400)),
                ('to_who', models.IntegerField(default=0)),
                ('who_do', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('who', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(default=0, max_length=10)),
                ('work_area', models.CharField(max_length=30, null=True)),
                ('week_day', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default=911, max_length=20)),
                ('name', models.CharField(default=0, max_length=30)),
                ('work_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Order_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Work_Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('last_change_time', models.DateTimeField(auto_now=True)),
                ('work_area', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('telephone_number', models.CharField(max_length=20)),
                ('dormitory_number', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('introduction', models.CharField(blank=True, default=None, max_length=200)),
                ('situation_order', models.IntegerField(default=0)),
                ('operator', models.CharField(default=None, max_length=200, null=True)),
                ('who_do', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='work_order_image',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_system.Work_Situation'),
        ),
    ]
