# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order_image',
            name='to_id',
            field=models.IntegerField(default=0),
        ),
    ]
