# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_system', '0002_work_order_image_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('who_do', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('record', models.CharField(max_length=400)),
            ],
        ),
    ]
