# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_system', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
