# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_system', '0005_check_in_hunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='who_do',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
